services:
  - type: web
    name: face_rec_service
    env: python
    plan: free
    branch: main
    root: face_rec_service
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /