import express from 'express';
import axios from 'axios';
import Student from '../models/Student.js';
import { verifyToken } from '../middleware/authMiddleware.js';

const router = express.Router();
const serviceUrl = (process.env.RECOMMENDATION_SERVICE_URL || 'http://127.0.0.1:8001').replace(/\/$/, '');
const serviceApiKey = process.env.RECOMMENDATION_API_KEY || '';
const normalize = (value) => String(value || '').trim().toLowerCase();

const fallbackRecommendations = async (request) => {
  const topN = Math.min(20, Math.max(1, Number(request.top_n) || 8));
  const requiredSkills = Array.isArray(request.required_skills) ? request.required_skills.map(normalize).filter(Boolean) : [];
  const preferredSkills = Array.isArray(request.preferred_skills) ? request.preferred_skills.map(normalize).filter(Boolean) : [];
  const department = normalize(request.department);
  const students = await Student.find({}).select('name department year cgpa profile_image verificationStatus faceVerificationStatus profileCompleteness skills').lean();

  const ranked = students.map((student) => {
    const studentSkills = (student.skills || []).map((skill) => normalize(typeof skill === 'string' ? skill : skill?.name));
    const allRequested = [...requiredSkills, ...preferredSkills].filter((skill, index, list) => skill && list.indexOf(skill) === index);
    const matched = allRequested.filter((skill) => studentSkills.includes(skill));
    const missing = requiredSkills.filter((skill) => !studentSkills.includes(skill));
    const skillScore = allRequested.length ? matched.length / allRequested.length : 0;
    const departmentScore = department && normalize(student.department) === department ? 1 : 0;
    const completeness = Math.min(1, Number(student.profileCompleteness || 0) / 100);
    const matchScore = skillScore * 0.65 + departmentScore * 0.2 + completeness * 0.15;
    return {
      student_id: String(student._id), name: student.name || 'Unknown Student', department: student.department || null,
      year: student.year || null, cgpa: student.cgpa ?? null, profile_image: student.profile_image || null,
      verification_status: student.verificationStatus || null, face_verification_status: student.faceVerificationStatus || null,
      profile_completeness: student.profileCompleteness ?? null, match_score: Number(matchScore.toFixed(4)),
      match_percent: Math.round(matchScore * 100), matched_skills: matched, missing_skills: missing,
      reasons: [departmentScore ? 'Same department' : '', matched.length ? `${matched.length} skill match${matched.length === 1 ? '' : 'es'}` : '', completeness >= 0.4 ? 'Profile is sufficiently complete' : ''].filter(Boolean),
      summary: 'Generated by the backend MongoDB fallback recommender.',
    };
  }).sort((a, b) => b.match_score - a.match_score).slice(0, topN);

  return { success: true, data: ranked, total: ranked.length, source: 'mongodb-fallback' };
};

router.post('/', verifyToken, async (req, res) => {
  if (req.user?.userType !== 'faculty' && req.user?.userType !== 'admin') return res.status(403).json({ success: false, message: 'Faculty or admin access required' });
  try {
    const response = await axios.post(`${serviceUrl}/recommendations`, req.body, { timeout: 15000, headers: serviceApiKey ? { 'X-Recommendation-Api-Key': serviceApiKey } : undefined });
    return res.status(response.status).json(response.data);
  } catch (error) {
    try {
      return res.json(await fallbackRecommendations(req.body || {}));
    } catch (fallbackError) {
      if (axios.isAxiosError(error) && error.response) return res.status(error.response.status).json({ success: false, message: error.response.data?.detail || error.response.data?.message || 'Recommendation service rejected the request' });
      return res.status(503).json({ success: false, message: fallbackError?.message || 'Recommendation service and fallback are unavailable' });
    }
  }
});

export default router;
